export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const FETCH_EVENT_FEEDBACKS = 'FETCH_EVENT_FEEDBACKS';
export const CREATE_EVENT_FEEDBACK = 'CREATE_EVENT_FEEDBACK';
export const DELETE_EVENT_FEEDBACK = 'DELETE_EVENT_FEEDBACK';

export const FETCH_BLOGS = 'FETCH_BLOGS';
export const CREATE_BLOG = 'CREATE_BLOG';
export const UPDATE_BLOG = 'UPDATE_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';

export const FETCH_MHPS = 'FETCH_MHPS';
export const UPDATE_MHP = 'UPDATE_MHP';
export const FETCH_MHP_FEEDBACKS = 'FETCH_MHP_FEEDBACKS';
export const CREATE_MHP_FEEDBACK = 'CREATE_MHP_FEEDBACK';
export const DELETE_MHP_FEEDBACK = 'DELETE_MHP_FEEDBACK';

export const FETCH_TERMS = 'FETCH_TERMS';
export const UPDATE_TERMS = 'UPDATE_TERMS';

export const FETCH_THOUGHTS = 'FETCH_THOUGHTS';
export const CREATE_THOUGHT = 'CREATE_THOUGHT';
export const DELETE_THOUGHT = 'DELETE_THOUGHT';

export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
